# Generated by Django 4.2.5 on 2023-09-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btype', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('btype',),
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=400)),
                ('url', models.TextField()),
                ('fecha', models.DateField()),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
    ]
